apiVersion: v1
kind: Service
metadata:
  name: velucid-openfga
  namespace: velucid
  labels:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: authorization
    app.kubernetes.io/name: openfga
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 8081
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: authorization
    app.kubernetes.io/name: openfga
