apiVersion: v1
kind: ConfigMap
metadata:
  name: velucid-tempo-config
  namespace: velucid
  labels:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: observability
    app.kubernetes.io/name: tempo
data:
  tempo.yaml: |
    stream_over_http_enabled: true

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    dist:
      ring:
        instance_addr: 127.0.0.1
        replication_factor: 1
        kvstore:
          store: inmemory

    storage:
      trace:
        backend: local
        wal:
          path: /var/tempo/wal
        local:
          path: /var/tempo/blocks

    limits:
      max_bytes_per_trace: 5000000

    overrides:
      max_bytes_per_trace: 5000000