apiVersion: v1
kind: Service
metadata:
  name: velucid-tempo
  namespace: velucid
  labels:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: observability
    app.kubernetes.io/name: tempo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: 9095
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
  selector:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: observability
    app.kubernetes.io/name: tempo