apiVersion: v1
kind: Service
metadata:
  name: velucid-kurrentdb
  namespace: velucid
  labels:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: eventstore
    app.kubernetes.io/name: kurrentdb
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 2113
      targetPort: 2113
      protocol: TCP
    - name: tcp
      port: 1113
      targetPort: 1113
      protocol: TCP
  selector:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: eventstore
    app.kubernetes.io/name: kurrentdb
