FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build
WORKDIR /src
COPY ["Velucid.Silo/Velucid.Silo.csproj", "Velucid.Silo/"]
RUN dotnet restore "Velucid.Silo/Velucid.Silo.csproj"
COPY . .
WORKDIR /src/Velucid.Silo
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview
WORKDIR /app
COPY --from=build /app .
EXPOSE 5000 11111 30000
ENTRYPOINT ["dotnet", "Velucid.Silo.dll"]
