// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vut.ReadModel.Migrations;

#nullable disable

namespace Vut.ReadModel.Migrations.Migrations
{
    [DbContext(typeof(ReadModelDbContext))]
    [Migration("20260507163741_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vut.ReadModel.Migrations.Entities.OrgInvitationProjection", b =>
                {
                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("OrgId", "Email")
                        .HasName("pk_org_invitation_projection");

                    b.HasIndex("Email", "Status")
                        .HasDatabaseName("ix_org_invitation_projection_email_status");

                    b.ToTable("org_invitation_projection", "public", t =>
                        {
                            t.HasCheckConstraint("ck_invitation_role", "role IN ('Owner', 'Member')");

                            t.HasCheckConstraint("ck_invitation_status", "status IN ('Pending', 'Accepted', 'Declined')");
                        });
                });

            modelBuilder.Entity("Vut.ReadModel.Migrations.Entities.OrgMemberProjection", b =>
                {
                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("OrgId", "UserId")
                        .HasName("pk_org_member_projection");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_org_member_projection_user_id");

                    b.ToTable("org_member_projection", "public", t =>
                        {
                            t.HasCheckConstraint("ck_org_member_role", "role IN ('Owner', 'Member')");
                        });
                });

            modelBuilder.Entity("Vut.ReadModel.Migrations.Entities.OrgProjection", b =>
                {
                    b.Property<Guid>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("OrgId")
                        .HasName("pk_org_projection");

                    b.ToTable("org_projection", "public");
                });

            modelBuilder.Entity("Vut.ReadModel.Migrations.Entities.ProjectionCheckpoint", b =>
                {
                    b.Property<string>("ProjectorName")
                        .HasColumnType("text")
                        .HasColumnName("projector_name");

                    b.Property<string>("Topic")
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<int>("PartitionId")
                        .HasColumnType("integer")
                        .HasColumnName("partition_id");

                    b.Property<long>("LastOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("last_offset");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectorName", "Topic", "PartitionId")
                        .HasName("pk_projection_checkpoint");

                    b.ToTable("projection_checkpoint", "public");
                });

            modelBuilder.Entity("Vut.ReadModel.Migrations.Entities.UserIdentity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ProviderId")
                        .HasColumnType("text")
                        .HasColumnName("provider_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("LinkedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_name");

                    b.HasKey("UserId", "ProviderId")
                        .HasName("pk_user_identity");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_user_identity_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("ProviderId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_identity_provider_id");

                    b.ToTable("user_identity", "public");
                });

            modelBuilder.Entity("Vut.ReadModel.Migrations.Entities.UserOrgProjection", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("UserId", "OrgId")
                        .HasName("pk_user_org_projection");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_user_org_projection_org_id");

                    b.ToTable("user_org_projection", "public");
                });

            modelBuilder.Entity("Vut.ReadModel.Migrations.Entities.UserProjection", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("UserId")
                        .HasName("pk_user_projection");

                    b.ToTable("user_projection", "public");
                });

            modelBuilder.Entity("Vut.ReadModel.Migrations.Entities.OrgInvitationProjection", b =>
                {
                    b.HasOne("Vut.ReadModel.Migrations.Entities.OrgProjection", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_invitation_projection_org_projection_org_id");
                });

            modelBuilder.Entity("Vut.ReadModel.Migrations.Entities.OrgMemberProjection", b =>
                {
                    b.HasOne("Vut.ReadModel.Migrations.Entities.OrgProjection", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_member_projection_org_projection_org_id");

                    b.HasOne("Vut.ReadModel.Migrations.Entities.UserProjection", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_org_member_projection_user_projection_user_id");
                });

            modelBuilder.Entity("Vut.ReadModel.Migrations.Entities.UserIdentity", b =>
                {
                    b.HasOne("Vut.ReadModel.Migrations.Entities.UserProjection", "User")
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_identity_user_projection_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vut.ReadModel.Migrations.Entities.UserOrgProjection", b =>
                {
                    b.HasOne("Vut.ReadModel.Migrations.Entities.OrgProjection", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_org_projection_org_projection_org_id");

                    b.HasOne("Vut.ReadModel.Migrations.Entities.UserProjection", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_org_projection_user_projection_user_id");
                });

            modelBuilder.Entity("Vut.ReadModel.Migrations.Entities.UserProjection", b =>
                {
                    b.Navigation("Identities");
                });
#pragma warning restore 612, 618
        }
    }
}
