apiVersion: apps/v1
kind: Deployment
metadata:
  name: velucid-projector-service
  namespace: velucid
  labels:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: projector
    app.kubernetes.io/name: projector-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/part-of: velucid
      app.kubernetes.io/component: projector
      app.kubernetes.io/name: projector-service
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: velucid
        app.kubernetes.io/component: projector
        app.kubernetes.io/name: projector-service
    spec:
      initContainers:
        - name: run-migrations
          image: ghcr.io/lekhasy/vut/migrations:6993e4e
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: velucid-postgresql-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: velucid-postgresql-secret
                  key: POSTGRES_PASSWORD
            - name: CONNECTION_STRING
              value: "Host=velucid-postgresql;Database=velucid_readmodel;Username=$(POSTGRES_USERNAME);Password=$(POSTGRES_PASSWORD)"
      containers:
        - name: projector-service
          image: ghcr.io/lekhasy/vut/projector-service:6993e4e
          imagePullPolicy: IfNotPresent
          env:
            - name: KurrentDb__ConnectionString
              value: "esdb://velucid-kurrentdb:2113?tls=false"
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: velucid-postgresql-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: velucid-postgresql-secret
                  key: POSTGRES_PASSWORD
            - name: ConnectionStrings__PostgreSQL
              value: "Host=velucid-postgresql;Database=velucid_readmodel;Username=$(POSTGRES_USERNAME);Password=$(POSTGRES_PASSWORD)"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
