apiVersion: v1
kind: Service
metadata:
  name: platform-loki
  namespace: platform-observability
  labels:
    app.kubernetes.io/part-of: platform-observability
    app.kubernetes.io/component: observability
    app.kubernetes.io/name: loki
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: platform-observability
    app.kubernetes.io/component: observability
    app.kubernetes.io/name: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      protocol: TCP
    - name: grpc
      port: 9096
      targetPort: 9096
      protocol: TCP