apiVersion: v1
kind: Service
metadata:
  name: velucid-frontend
  namespace: velucid
  labels:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: frontend
