apiVersion: v1
kind: Service
metadata:
  name: platform-grafana
  namespace: platform-observability
  labels:
    app.kubernetes.io/part-of: platform-observability
    app.kubernetes.io/component: observability
    app.kubernetes.io/name: grafana
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: platform-observability
    app.kubernetes.io/component: observability
    app.kubernetes.io/name: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP