apiVersion: apps/v1
kind: Deployment
metadata:
  name: velucid-pgadmin
  namespace: velucid
  labels:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: database-admin
    app.kubernetes.io/name: pgadmin
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/part-of: velucid
      app.kubernetes.io/component: database-admin
      app.kubernetes.io/name: pgadmin
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: velucid
        app.kubernetes.io/component: database-admin
        app.kubernetes.io/name: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@velucid.app"
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: velucid-postgresql-secret
                  key: POSTGRES_PASSWORD
            - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
              value: "True"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
