apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velucid-pgadmin-ingress
  namespace: velucid
  labels:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: database-admin
    app.kubernetes.io/name: pgadmin
spec:
  ingressClassName: traefik
  rules:
    - host: pgadmin.velucid.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: velucid-pgadmin
                port:
                  number: 80
