apiVersion: v1
kind: Service
metadata:
  name: velucid-postgresql
  namespace: velucid
  labels:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: database
    app.kubernetes.io/name: postgresql
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: database
    app.kubernetes.io/name: postgresql
