apiVersion: v1
kind: ConfigMap
metadata:
  name: velucid-openfga-config
  namespace: velucid
  labels:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: authorization
    app.kubernetes.io/name: openfga
data:
  OPENFGA_STORE_NAME: "velucid"
