apiVersion: v1
kind: Secret
metadata:
  name: velucid-openfga-secret
  namespace: velucid
  labels:
    app.kubernetes.io/part-of: velucid
    app.kubernetes.io/component: authorization
    app.kubernetes.io/name: openfga
type: Opaque
stringData:
  OPENFGA_DATASTORE_URI: "postgres://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@velucid-postgresql:5432/velucid_openfga?sslmode=disable"
